<?php

namespace Database\Seeders;

use App\Models\Business;
use Illuminate\Database\Seeder;

class BusinessDetailSeeder extends Seeder
{
    public function run(): void
    {
        $this->seedHotelDetails();
        $this->seedRestaurantDetails();
    }

    private function features(array $list): array
    {
        return array_map(fn ($item) => ['text' => $item], $list);
    }

    private function seedHotelDetails(): void
    {
        $hotels = [
            'hotel-the-kantipur' => [
                'description' => '<p>Hotel The Kantipur stands as one of Pokhara\'s finest lakeside properties, offering an unrivalled combination of comfort, luxury, and natural beauty. Situated on the serene banks of Phewa Lake, the hotel commands breathtaking panoramic views of the Annapurna mountain range, making every sunrise a memorable experience.</p><p>The hotel features elegantly designed rooms and suites, each thoughtfully furnished with modern amenities while retaining a warm Nepali character. Our rooftop terrace and lakeside restaurant serve an extensive menu of Nepali, Indian, and continental cuisine, with fresh ingredients sourced from local farms.</p>',
                'opening_hours' => 'Open 24 hours / 7 days a week',
                'features' => $this->features(['Free Wi-Fi in all rooms', 'Lakeside swimming pool', 'Rooftop restaurant & bar', 'Spa & wellness centre', 'Mountain view rooms', 'Free airport transfer', '24/7 room service', 'Air conditioning', 'Flat-screen TV', 'Daily housekeeping', 'Safe deposit box', 'Laundry service', 'Tour desk & booking', 'Currency exchange', 'Conference facilities', 'Private parking']),
                'is_verified' => true,
            ],
            'hotel-iceland' => [
                'description' => '<p>Hotel Iceland Pokhara is a premium modern property strategically located in the heart of Lakeside, Pokhara. The hotel is celebrated for its stunning rooftop infinity pool that appears to merge with Phewa Lake, offering guests an unparalleled aquatic experience against a backdrop of snow-capped peaks.</p><p>Each room at Hotel Iceland is designed with contemporary elegance, featuring floor-to-ceiling windows to maximise the mountain and lake views. The multi-cuisine restaurant on the ground floor serves breakfast buffets and à-la-carte meals throughout the day.</p>',
                'opening_hours' => 'Check-in: 2:00 PM | Check-out: 12:00 PM | Reception: 24 hours',
                'features' => $this->features(['Rooftop infinity pool', 'Free high-speed Wi-Fi', 'Mountain-view rooms', 'Multi-cuisine restaurant', 'Rooftop bar & lounge', 'Air conditioning', 'Flat-screen TV', 'In-room safe', '24/7 front desk', 'Room service', 'Fitness centre', 'Massage services', 'Bicycle rental', 'Free parking', 'Luggage storage', 'Airport shuttle']),
                'is_verified' => true,
            ],
            'hotel-barahi-pokhara' => [
                'description' => '<p>Hotel Barahi Pokhara is an iconic 4-star property sitting majestically on a small island peninsula at the southern end of Phewa Lake. Accessible by boat from the lakeside promenade, it offers a uniquely secluded experience despite being moments from the vibrant Lakeside district.</p><p>The hotel boasts lush tropical gardens, an outdoor swimming pool surrounded by palm trees, and a spacious spa offering traditional Ayurvedic treatments. The signature Baithak restaurant is renowned throughout Pokhara for its authentic Newari cuisine and lakeside ambience.</p>',
                'opening_hours' => 'Open 24 hours | Boat transfer: 6:00 AM – 10:00 PM',
                'features' => $this->features(['Island location on Phewa Lake', 'Outdoor swimming pool', 'Ayurvedic spa', 'Newari cuisine restaurant', 'Boat transfer service', 'Conference centre (300 pax)', 'Tropical garden', 'Yoga & meditation', 'Free Wi-Fi', 'Mountain-view rooms', 'Air conditioning', 'Room service', 'Wedding venue', 'Gift shop', 'Tour desk', 'Children\'s play area']),
                'is_verified' => true,
            ],
            'temple-tree-resort-spa' => [
                'description' => '<p>Temple Tree Resort & Spa is Pokhara\'s premier luxury boutique property, an oasis of tranquillity set among ancient trees and tropical gardens just steps from the Lakeside promenade. The resort was built to honour the natural beauty of the Pokhara Valley, and every architectural detail reflects this philosophy.</p><p>Accommodation comprises individually designed deluxe rooms, junior suites, and a magnificent presidential suite, each featuring handcrafted Nepali art, private balconies, and cutting-edge amenities. The resort\'s award-winning Atithi Spa offers over 30 treatments, from traditional Nepali healing therapies to international wellness rituals.</p>',
                'opening_hours' => 'Check-in: 2:00 PM | Check-out: 11:00 AM | Spa: 7:00 AM – 9:00 PM',
                'features' => $this->features(['Award-winning Atithi Spa', 'Skydeck 360° views', 'Elixir fine dining restaurant', 'Boutique accommodation', 'Infinity pool', 'Yoga pavilion', 'Private balconies', 'Handcrafted Nepali décor', 'Presidential suite', 'In-room Jacuzzi (suites)', 'Free Wi-Fi', 'Personal butler service', 'Evening cultural shows', 'Trekking concierge', 'Heli-tour booking', 'Luxury transfers']),
                'is_verified' => true,
            ],
            'hotel-pokhara-grande' => [
                'description' => '<p>Hotel Pokhara Grande is the valley\'s largest 5-star property, a world-class destination for both leisure and MICE travellers. Located at Birauta Chowk, Pardi — just 3 km from the international airport and 2 km from Lakeside — the hotel combines unmatched convenience with premium facilities.</p><p>The hotel\'s 200+ rooms and suites offer spectacular views of the Annapurna range. Dining options span four outlets: the all-day Dhungri restaurant, Thakali Kitchen, Celsius the rooftop bar, and the Himalayan Bakery & Café. Conference and banqueting facilities include a grand ballroom accommodating 1,000 guests.</p>',
                'opening_hours' => 'Open 24 hours | Restaurants: 6:30 AM – 11:00 PM',
                'features' => $this->features(['5-star luxury facilities', 'Grand ballroom (1,000 pax)', '6 conference breakout rooms', 'Rooftop infinity pool', 'Celsius rooftop bar', 'Thakali Kitchen restaurant', 'Full-service spa', 'Fitness centre', 'Tennis court', 'Casino', 'Business centre', 'Helipad access', 'Airport shuttle', 'Free high-speed Wi-Fi', 'Concierge & tour desk', 'Valet parking']),
                'is_verified' => true,
            ],
            'hotel-white-pearl' => [
                'description' => '<p>Hotel White Pearl is an elegant lakeside property that lives up to its name — a gem of a hotel offering refined comfort and outstanding mountain views. The hotel is positioned on the quieter northern stretch of Lakeside, giving guests a sense of seclusion while still being within easy walking distance of shops, restaurants, and boat hire.</p><p>The property features meticulously maintained rooms with white linen and natural tones, a rooftop terrace with a panoramic Annapurna view, and a restaurant known for its fresh buffet breakfast and evening set menus. The attentive staff have earned consistent top ratings from guests on major travel platforms.</p>',
                'opening_hours' => 'Check-in: 2:00 PM | Check-out: 11:00 AM | Restaurant: 7:00 AM – 10:00 PM',
                'features' => $this->features(['Rooftop Annapurna panorama', 'Lakeside location', 'Buffet breakfast', 'Free high-speed Wi-Fi', 'Air conditioning', 'Flat-screen TV', '24-hour hot water', 'Tour & trek desk', 'Laundry service', 'Luggage storage', 'Currency exchange', 'Airport transfer']),
            ],
            'dahlia-boutique-hotel' => [
                'description' => '<p>Dahlia Boutique Hotel is a charming, independently owned property decorated in warm earthy tones with splashes of bold Nepali colour. The hotel has built a loyal following among boutique-seekers who want a more personal, characterful stay than chain hotels can offer. Each room is individually designed, making every visit a slightly different experience.</p><p>The hotel\'s garden café serves artisan coffee, fresh juices, and a short menu of breakfast and light lunch dishes. In the evenings, the rooftop becomes a relaxed social space where guests and locals mingle over local craft spirits and Nepali nibbles. The team is passionate about connecting guests with genuine local experiences.</p>',
                'opening_hours' => 'Check-in: 1:00 PM | Check-out: 11:00 AM | Café: 7:30 AM – 9:30 PM',
                'features' => $this->features(['Boutique individually designed rooms', 'Garden café', 'Rooftop evening social space', 'Artisan coffee', 'Free Wi-Fi', 'Air conditioning', 'Local experience concierge', 'Craft spirits bar', 'Daily housekeeping', 'Laundry service', 'Bicycle rental', 'Airport transfer']),
            ],
            'pokhara-choice-inn' => [
                'description' => '<p>Pokhara Choice Inn is a reliable, well-priced guesthouse that has earned its name as the sensible choice for budget and mid-range travellers who prioritise cleanliness, comfort, and a helpful service team. Centrally located in Lakeside, everything you need for a great Pokhara trip is within easy walking distance.</p><p>The inn offers a variety of room types from economy singles to spacious doubles with mountain views. A generous continental breakfast is served each morning, and the front desk team are on hand around the clock to help with any travel arrangements from trekking permits to paragliding bookings.</p>',
                'opening_hours' => 'Open 24 hours | Breakfast: 7:00 AM – 10:00 AM',
                'features' => $this->features(['Central Lakeside location', 'Continental breakfast included', '24-hour reception', 'Free Wi-Fi', 'Air conditioning', 'Clean & well-maintained rooms', 'Trekking permit assistance', 'Paragliding booking', 'Luggage storage', 'Laundry service', 'Currency exchange', 'Airport pickup available']),
            ],
            'hotel-blossom' => [
                'description' => '<p>Hotel Blossom brings a breath of fresh air to Pokhara\'s accommodation scene with its bright floral décor, blooming courtyard garden, and genuinely cheerful atmosphere. The hotel is especially popular with families and couples who appreciate the garden setting and the peaceful environment away from the main Lakeside commercial strip.</p><p>The blossom garden is the hotel\'s centrepiece — a beautifully maintained space with jasmine, bougainvillea, and marigolds framing stone benches and a small koi pond. The garden-view rooms open directly onto this space, making them among the most sought-after in the property.</p>',
                'opening_hours' => 'Check-in: 12:00 PM | Check-out: 11:00 AM | Restaurant: 7:00 AM – 9:30 PM',
                'features' => $this->features(['Blooming courtyard garden', 'Garden-view rooms', 'Koi pond & stone benches', 'Free Wi-Fi', 'Air conditioning', 'Family-friendly', 'Restaurant & café', 'Daily housekeeping', 'Laundry service', 'Tour desk', 'Luggage storage', 'Quiet residential location']),
            ],
            'hotel-grand-holiday' => [
                'description' => '<p>Hotel Grand Holiday delivers on its name with spacious, well-appointed rooms and a genuine holiday atmosphere. The hotel caters effectively to both leisure and business travellers with a full range of modern amenities, a large swimming pool, and dedicated conference facilities that are among the better-equipped in the Lakeside area.</p><p>The Grand Holiday\'s restaurant offers an extensive international menu served throughout the day, and the pool bar is a favourite afternoon spot. The hotel actively promotes active tourism by partnering with certified adventure operators to offer paragliding, rafting, and trekking packages at competitive rates.</p>',
                'opening_hours' => 'Open 24 hours | Pool: 7:00 AM – 8:00 PM | Restaurant: 7:00 AM – 10:30 PM',
                'features' => $this->features(['Swimming pool', 'Pool bar', 'Conference facilities', 'International restaurant', 'Adventure tour packages', 'Paragliding booking', 'Rafting arrangement', 'Free Wi-Fi', 'Air conditioning', 'Business centre', 'Laundry service', 'Airport transfer']),
            ],
            'hotel-middle-path-spa' => [
                'description' => '<p>Hotel Middle Path & Spa draws its name from the Buddhist concept of the Middle Way — a balanced approach to life that the hotel embodies through its combination of comfort, wellness, and mindful hospitality. The in-house spa is a genuine highlight, staffed by trained therapists offering traditional Nepali healing treatments alongside international wellness therapies.</p><p>The hotel occupies a leafy plot in Lakeside, with rooms arranged around a central garden courtyard. Morning yoga classes on the terrace are complimentary for all guests, and the spa\'s herbal steam room is available until 9 PM daily. The restaurant offers a health-conscious menu alongside more indulgent options.</p>',
                'opening_hours' => 'Check-in: 12:00 PM | Check-out: 11:00 AM | Spa: 8:00 AM – 9:00 PM',
                'features' => $this->features(['In-house spa & wellness', 'Traditional Nepali treatments', 'Morning yoga (complimentary)', 'Herbal steam room', 'Garden courtyard', 'Health-conscious menu', 'Free Wi-Fi', 'Air conditioning', 'Meditation sessions', 'Laundry service', 'Tour desk', 'Airport transfer']),
            ],
            'hotel-point' => [
                'description' => '<p>Hotel Point is a straightforward, no-nonsense accommodation option that consistently delivers exactly what budget and mid-range travellers need: a clean bed, a hot shower, reliable Wi-Fi, and a helpful team to assist with travel plans. Its central Lakeside location puts the lake, restaurants, shops, and trekking agencies within a 5-minute walk.</p><p>The hotel offers a range of room sizes from compact singles to spacious family rooms. The rooftop terrace is a favourite spot for sunset watching, and the in-house restaurant serves a solid selection of Nepali, Indian, and continental dishes at very competitive prices.</p>',
                'opening_hours' => 'Open 24 hours | Restaurant: 7:30 AM – 10:00 PM',
                'features' => $this->features(['Central Lakeside location', 'Rooftop sunset terrace', 'Budget-friendly pricing', 'Free Wi-Fi', 'Air conditioning', 'Hot water 24 hours', 'Restaurant & bar', 'Trekking assistance', 'Luggage storage', 'Laundry service', 'Currency exchange', 'Tour booking service']),
            ],
            'bodhi-suites-boutique-hotel' => [
                'description' => '<p>Bodhi Suites Boutique Hotel and Spa is Pokhara\'s most spiritually inspired boutique property — a serene sanctuary named after the sacred Bodhi tree under which the Buddha attained enlightenment. The hotel combines Buddhist aesthetic principles with genuine luxury to create an atmosphere of calm sophistication.</p><p>Each suite is a self-contained retreat, featuring handcrafted Tibetan furniture, meditation cushions, and curated local art. The in-house spa specialises in Tibetan singing bowl therapy, Reiki, and Ayurvedic treatments. Daily guided meditation and philosophical discussion sessions are available for interested guests.</p>',
                'opening_hours' => 'Check-in: 2:00 PM | Check-out: 12:00 PM | Spa: 8:00 AM – 8:00 PM',
                'features' => $this->features(['Buddhist-inspired boutique suites', 'Tibetan furniture & art', 'Singing bowl therapy spa', 'Reiki & Ayurveda treatments', 'Daily guided meditation', 'Philosophical discussion evenings', 'Meditation cushions in every room', 'Free Wi-Fi', 'Air conditioning', 'Personalised butler service', 'Organic restaurant', 'Airport transfers']),
                'is_verified' => true,
            ],
            'hotel-mount-view-pokhara' => [
                'description' => '<p>Hotel Mount View Pokhara is exactly what its name promises — a property that gives every guest the mountain experience they came to Nepal for. With its elevated position on the northern edge of Lakeside and a clear north-facing aspect, the hotel offers one of the most unobstructed views of the Annapurna massif available in the city.</p><p>Rooms are modern, clean, and thoughtfully furnished, with large windows framing the mountain panorama. The rooftop breakfast terrace — where guests eat among the mountain silhouettes every morning — has become one of Pokhara\'s most photographed dining spots on social media.</p>',
                'opening_hours' => 'Check-in: 12:00 PM | Check-out: 11:00 AM | Restaurant: 6:30 AM – 10:00 PM',
                'features' => $this->features(['Annapurna mountain views', 'Rooftop breakfast terrace', 'North-facing rooms', 'Free high-speed Wi-Fi', 'Air conditioning', 'Flat-screen TV', '24-hour reception', 'Room service', 'Trek permit assistance', 'Laundry service', 'Luggage storage', 'Airport transfer']),
            ],
            'da-yatra-courtyard-hotel-resort' => [
                'description' => '<p>Da Yatra Courtyard Hotel & Resort is an exceptional property that reimagines the concept of a boutique hotel through the lens of the Nepali yatra — a sacred journey. The hotel design references the architecture and spiritual iconography of the Kathmandu Valley, transported to the lakeside setting of Pokhara with extraordinary attention to detail.</p><p>The central courtyard is a masterpiece of Newari craftsmanship, with intricately carved wooden peacock windows, stone water spouts, and a terraced garden. Each accommodation block surrounds this courtyard, ensuring that every room benefits from its tranquil atmosphere. The restaurant serves traditional Newari feast menus for groups on reservation.</p>',
                'opening_hours' => 'Check-in: 2:00 PM | Check-out: 12:00 PM | Restaurant: 7:00 AM – 10:00 PM',
                'features' => $this->features(['Newari-inspired courtyard architecture', 'Carved peacock windows', 'Traditional Newari feast menus', 'Heritage stone water spouts', 'Terrace garden', 'Cultural briefing on arrival', 'Free Wi-Fi', 'Air conditioning', 'Boutique rooms', 'Tour desk', 'Laundry service', 'Airport transfer']),
            ],
            'hotel-snowland' => [
                'description' => '<p>Hotel Snowland is a charming Lakeside hotel that has welcomed trekkers and tourists for over three decades. Its reputation rests on friendly family-run hospitality, thoughtfully maintained rooms, and a prime location just a short walk from the Lakeside waterfront and the city\'s best restaurants and shops.</p><p>The hotel offers a range of room categories to suit different budgets, from standard singles to spacious deluxe rooms with mountain views. The rooftop terrace is a favourite spot for guests to relax over tea and watch the sun descend behind the Annapurna range in the evenings.</p>',
                'opening_hours' => 'Open 24 hours | Rooftop terrace: 7:00 AM – 9:00 PM',
                'features' => $this->features(['Family-run since 1990s', 'Rooftop mountain-view terrace', 'Expert trek planning desk', 'Free Wi-Fi', 'Room service', 'Air conditioning (deluxe rooms)', 'Laundry service', 'Luggage storage', 'Currency exchange', '24-hour hot water', 'Daily housekeeping', 'Motorbike rental']),
            ],
            'hotel-fewa-trip' => [
                'description' => '<p>Hotel Fewa Trip is a lakeside property celebrating Pokhara\'s most iconic landmark — the legendary Phewa Lake whose Nepali name this hotel proudly carries. Sitting directly opposite the lake\'s eastern shore, the hotel makes Phewa Lake the centrepiece of every guest\'s stay, from morning boat rides to evening lakeside strolls.</p><p>The hotel operates its own fleet of traditional wooden rowboats for guest use, available from 6 AM to 6 PM daily. A lakeside terrace restaurant serves breakfast and light meals with the lake always in view. The hotel specialises in arranging bespoke Annapurna region experiences, from day hikes to multi-week expeditions.</p>',
                'opening_hours' => 'Open 24 hours | Lakeside restaurant: 6:30 AM – 9:00 PM',
                'features' => $this->features(['Phewa Lake frontage', 'Own rowboat fleet', 'Lakeside terrace restaurant', 'Bespoke Annapurna experiences', 'Free Wi-Fi', 'Air conditioning', 'Mountain & lake views', 'Day hike arrangement', 'Multi-week expedition planning', 'Laundry service', 'Luggage storage', 'Airport transfer']),
            ],
            'hotel-lake-shore' => [
                'description' => '<p>Hotel Lake Shore occupies a prime position right on the shores of Phewa Lake, making it one of the most desirable locations in Pokhara for travellers who want to wake up to lakeside views every morning. The hotel\'s design is clean and contemporary, letting the natural setting take centre stage.</p><p>Every room has been designed to maximise the lake view, with wide windows, light-coloured furnishings, and minimal clutter. The shaded lakeside terrace is the hotel\'s social heart — a place where guests linger over tea, read, and watch the fishing boats cross the morning mist on the lake. Kayak rental is available directly at the hotel\'s private jetty.</p>',
                'opening_hours' => 'Check-in: 1:00 PM | Check-out: 11:00 AM | Terrace café: 6:30 AM – 9:30 PM',
                'features' => $this->features(['Direct Phewa Lake frontage', 'Private jetty', 'Kayak rental', 'Lake-view rooms', 'Shaded lakeside terrace', 'Contemporary design', 'Free Wi-Fi', 'Air conditioning', 'Flat-screen TV', 'Daily housekeeping', 'Laundry service', 'Airport transfer']),
            ],
            'hotel-trekkers-inn' => [
                'description' => '<p>Hotel Trekkers Inn was built by trekkers, for trekkers. The founder, a seasoned Annapurna Circuit veteran, designed every aspect of the property with the practical needs of mountain adventurers in mind — from the large communal drying room to the detailed trek information boards in the lobby.</p><p>Rooms are clean, comfortable, and priced to appeal to the budget-conscious adventure traveller. The Basecamp restaurant stays open from 5:30 AM for early-departure trekkers and offers substantial pre-dawn breakfasts alongside an extensive packed lunch menu. The hotel maintains a free library of trek guidebooks, topographic maps, and gear hire equipment.</p>',
                'opening_hours' => 'Basecamp restaurant: 5:30 AM – 10:30 PM | Reception: 24 hours',
                'features' => $this->features(['Trekker-focused design', 'Heated gear drying room', 'Trek info boards in lobby', 'Early 5:30 AM breakfast', 'Packed lunch preparation', 'Free guidebook library', 'Topographic map collection', 'Gear hire available', 'Free Wi-Fi', 'Hot water 24 hours', 'Luggage storage', 'Group booking discounts']),
            ],
            'hotel-splendid-view' => [
                'description' => '<p>Hotel Splendid View does exactly what it says — from its elevated position above the valley floor, the hotel delivers some of the most spectacular, wide-angle views of the Annapurna range to be found from any Pokhara accommodation. Guests consistently describe their first sight of the mountains from the rooftop as a life-changing moment.</p><p>The hotel\'s hilltop location also means fresher air, greater quiet, and a genuine sense of being in the mountains rather than in a city. A short garden path leads to a private viewpoint used for sunrise photography, and the hotel maintains a telescope on the rooftop for stargazing on clear mountain nights.</p>',
                'opening_hours' => 'Check-in: 1:00 PM | Check-out: 11:00 AM | Restaurant: 6:00 AM – 10:00 PM',
                'features' => $this->features(['360° Annapurna panorama', 'Hilltop elevated position', 'Private sunrise viewpoint', 'Rooftop telescope for stargazing', 'Fresh mountain air', 'Quiet hilltop setting', 'Free Wi-Fi', 'Air conditioning', 'Restaurant & bar', 'Guided dawn hike service', 'Laundry service', 'Airport transfer']),
            ],
            'hotel-peninsula-pokhara' => [
                'description' => '<p>Hotel Peninsula Pokhara takes its name from its distinctive position on a small land projection reaching into the calm southern waters of Phewa Lake. This semi-island setting gives the hotel three-sided lake views that make it genuinely unique in Pokhara\'s accommodation landscape.</p><p>The hotel has recently been renovated to a boutique 4-star standard, with rooms featuring locally crafted furniture, mountain and lake views from every window, and spacious marble bathrooms. The lakeside restaurant is particularly renowned for its fresh fish dishes prepared with daily catches from the lake.</p>',
                'opening_hours' => 'Check-in: 2:00 PM | Check-out: 12:00 PM | Restaurant: 7:00 AM – 10:30 PM',
                'features' => $this->features(['Peninsula lake position', 'Three-sided lake views', 'Fresh lake fish restaurant', 'Boutique 4-star renovation', 'Lake-view rooms', 'Marble bathrooms', 'Free Wi-Fi', 'Air conditioning', 'Swimming pool', 'Boat hire', 'Room service', 'Airport transfer']),
            ],
            'hotel-portland' => [
                'description' => '<p>Hotel Portland is a contemporary property that brings a touch of international style to Pokhara\'s Lakeside district. With a name that nods to the owner\'s formative years spent in the Pacific Northwest, the hotel blends clean Northwest-modern aesthetics with warm Nepali hospitality — polished concrete, natural wood, and locally handwoven textiles in harmonious combination.</p><p>The hotel is home to the Portland Coffee Roastery, a specialty coffee concept that has developed a dedicated following among Pokhara\'s growing café culture community. The roastery operates visible in-house roasting from Tuesday to Sunday, and the resulting single-origin Nepali espresso is among the finest coffee available in the region.</p>',
                'opening_hours' => 'Check-in: 2:00 PM | Check-out: 11:00 AM | Coffee Roastery: 7:00 AM – 6:00 PM',
                'features' => $this->features(['Portland Coffee Roastery in-house', 'Specialty single-origin coffee', 'Visible in-house roasting', 'Contemporary Northwest design', 'Natural wood & concrete', 'Free high-speed Wi-Fi', 'Air conditioning', 'Designer rooms', 'Craft beer selection', 'Tour desk', 'Laundry service', 'Airport transfer']),
            ],
            'hotel-lake-star' => [
                'description' => '<p>Hotel Lake Star is a reliable 3-star lakeside property offering clean, comfortable accommodation at fair prices. Its position on the Phewa Lake waterfront means guests can step directly from the hotel onto rowing boats and pedal boats for self-guided lake exploration.</p><p>The Lake Star restaurant is a popular breakfast and lunch spot for both hotel guests and day visitors, with the lakeside terrace always busy on sunny mornings. The hotel is also a useful staging point for the boat ride to the World Peace Stupa — a must-do activity in Pokhara that the hotel can organise at any time of day.</p>',
                'opening_hours' => 'Open 24 hours | Lakeside restaurant: 6:30 AM – 9:30 PM',
                'features' => $this->features(['Direct Phewa Lake waterfront', 'Rowing & pedal boat access', 'Kayaking & paddleboarding', 'World Peace Stupa boat trips', 'Lakeside terrace restaurant', 'Free Wi-Fi', 'Air conditioning', '24-hour reception', 'Room service', 'Luggage storage', 'Laundry service', 'Currency exchange']),
            ],
            'hotel-noble-inn' => [
                'description' => '<p>Hotel Noble Inn is a well-established, mid-scale property that has built its reputation on consistent quality and genuine warmth of service. The "noble" in the name reflects the hotel\'s quiet dignity — it does not try to be flashy or trendy but simply delivers a high-quality stay at a fair price, every time.</p><p>The inn offers 28 well-appointed rooms across three categories. The top-floor Panorama rooms have partial Annapurna views and are the most popular. The Noble Restaurant is a Lakeside staple, particularly known for its wood-fired pizzas and hearty Nepali breakfasts.</p>',
                'opening_hours' => 'Open 24 hours | Noble Restaurant: 7:00 AM – 10:30 PM',
                'features' => $this->features(['Panorama rooms with Annapurna views', 'Wood-fired pizza restaurant', 'Hearty Nepali breakfast', 'Free Wi-Fi', 'Air conditioning', 'Daily housekeeping', '24-hour hot water', 'Tour desk', 'Laundry service', 'Currency exchange', 'Luggage storage', 'Airport transfer']),
            ],
            'hotel-forest-lake' => [
                'description' => '<p>Hotel Forest Lake sits at the intersection of forest and lake — surrounded on three sides by the dense forest of the Pokhara Valley foothills while overlooking a quiet inlet of Phewa Lake on the fourth. This exceptional natural setting makes it the most immersive nature-focused accommodation option in the Lakeside area.</p><p>Birdwatchers will find the hotel particularly rewarding — over 60 species have been recorded in the hotel garden and adjacent forest, including rare Himalayan species that visitors travel specifically to observe. Morning and evening guided bird-watching walks are organised daily. The wooden deck restaurant overlooks the forest canopy and the lake beyond.</p>',
                'opening_hours' => 'Check-in: 1:00 PM | Check-out: 11:00 AM | Restaurant: 7:00 AM – 9:30 PM',
                'features' => $this->features(['Forest & lake setting', '60+ bird species on site', 'Daily bird-watching walks', 'Wooden deck restaurant', 'Nature immersion', 'Private forest trails', 'Free Wi-Fi', 'Eco-friendly operations', 'Air conditioning', 'Quiet & peaceful', 'Laundry service', 'Airport transfer']),
            ],
            'bar-peepal-resort' => [
                'description' => '<p>Bar Peepal Resort takes its name from the sacred peepal tree — a species under which sages and travellers have rested for millennia, a symbol of shade, wisdom, and community. True to this spirit, the resort centres around a magnificent 200-year-old peepal tree whose canopy shelters the central courtyard and outdoor dining area.</p><p>The resort offers a range of cottages and rooms arranged around the central tree, each with private sit-outs and views of the tree or the garden beyond. The restaurant beneath the peepal canopy is one of Pokhara\'s most atmospheric dining experiences, particularly at night when the tree is lit with soft golden light.</p>',
                'opening_hours' => 'Check-in: 1:00 PM | Check-out: 11:00 AM | Restaurant: 7:00 AM – 10:00 PM',
                'features' => $this->features(['200-year-old peepal tree centrepiece', 'Garden cottages & rooms', 'Under-canopy restaurant', 'Courtyard atmosphere', 'Private sit-outs', 'Free Wi-Fi', 'Air conditioning', 'Yoga on the lawn', 'Cultural evenings', 'Laundry service', 'Tour desk', 'Airport transfer']),
            ],
            'hotel-basanta-inn' => [
                'description' => '<p>Hotel Basanta Inn (Basanta meaning "spring" in Nepali) brings year-round freshness and colour to Pokhara\'s accommodation scene with its flower-filled garden and bright, cheerfully decorated rooms. The family that runs the inn takes genuine pride in their property and their guests are treated with the warmth of family members rather than paying customers.</p><p>The inn is particularly popular with returning travellers who appreciate the consistency of the friendly service and the excellent value. The garden seating area is a favourite morning spot, where home-made yoghurt and fresh mango lassi are served alongside a full breakfast menu.</p>',
                'opening_hours' => 'Open all day | Kitchen: 7:00 AM – 9:30 PM',
                'features' => $this->features(['Family-run inn', 'Flower garden', 'Home-made yoghurt & lassi', 'Garden breakfast seating', 'Free Wi-Fi', 'Air conditioning', 'Clean & comfortable rooms', 'Excellent value pricing', 'Laundry service', 'Luggage storage', 'Trek arrangement', 'Currency exchange']),
            ],
            'hotel-orchid' => [
                'description' => '<p>Hotel Orchid is a sophisticated mid-range property whose interior design draws inspiration from the orchid flower — a symbol of refined beauty, rare quality, and graceful elegance. Over 40 varieties of live orchid are cultivated in the hotel\'s greenhouse and displayed throughout the property, creating an atmosphere of natural luxury.</p><p>The hotel is known for its exceptional level of personal service, with a guest-to-staff ratio that allows for a genuinely attentive experience. The in-house Orchid Spa uses orchid-extract treatments developed exclusively for the property, including the signature Himalayan Orchid Facial.</p>',
                'opening_hours' => 'Check-in: 2:00 PM | Check-out: 12:00 PM | Orchid Spa: 9:00 AM – 8:00 PM',
                'features' => $this->features(['Live orchid display throughout', 'Orchid greenhouse on-site', 'Orchid Spa & treatments', 'Signature Himalayan Orchid Facial', 'High staff-to-guest ratio', 'Luxury rooms', 'Free Wi-Fi', 'Air conditioning', 'Premium toiletries', 'Restaurant', 'Laundry & dry cleaning', 'Airport transfer']),
            ],
            'queens-park-hotel' => [
                'description' => '<p>Queens Park Hotel is a characterful 3-star hotel set in a spacious property with a large garden park — an increasingly rare feature in the growing city of Pokhara. The hotel\'s gardens are maintained to an exceptional standard, with manicured lawns, mature trees providing natural shade, and a series of pavilion seating areas ideal for outdoor relaxation.</p><p>The hotel has been a popular choice for wedding receptions and cultural events for decades, thanks to its large event lawn and elegant indoor banquet hall. Leisure guests appreciate the garden\'s tranquillity, the swimming pool, and the helpful in-house travel desk that can arrange any activity in the Annapurna region.</p>',
                'opening_hours' => 'Open 24 hours | Restaurant: 7:00 AM – 10:30 PM | Pool: 7:00 AM – 7:00 PM',
                'features' => $this->features(['Large garden park', 'Swimming pool', 'Wedding & event lawn', 'Indoor banquet hall', 'Manicured gardens', 'Outdoor pavilions', 'Free Wi-Fi', 'Air conditioning', 'Restaurant & bar', 'In-house travel desk', 'Free parking', 'Laundry service']),
            ],
            'raniban-arcade' => [
                'description' => '<p>Raniban Arcade is a distinctive property that takes its name from Raniban — the "Queen\'s Forest" — the lush protected woodland on the ridge above Pokhara. The hotel sits at the forest boundary, offering guests the privilege of direct access to forest trails from the back garden while remaining connected to the Lakeside district below.</p><p>Morning walks through the Raniban forest are a highlight of any stay — the dappled light through the sal trees, the chorus of birds at dawn, and the views of Phewa Lake glimpsed through the canopy are unforgettable. The hotel arranges guided nature walks, meditation in the forest, and forest yoga sessions for interested guests.</p>',
                'opening_hours' => 'Check-in: 1:00 PM | Check-out: 11:00 AM | Restaurant: 7:00 AM – 9:30 PM',
                'features' => $this->features(['Direct Raniban forest access', 'Forest trail from back garden', 'Guided nature walks', 'Forest yoga sessions', 'Forest meditation', 'Bird-watching on-site', 'Free Wi-Fi', 'Air conditioning', 'Restaurant', 'Garden seating', 'Laundry service', 'Airport transfer']),
            ],
            'peace-plaza-hotel' => [
                'description' => '<p>Peace Plaza Hotel lives up to its name as a quiet, well-priced property offering genuine peace in the heart of bustling Lakeside. Its leafy courtyard provides a natural sound buffer from the street, and the attentive staff contribute to an atmosphere of calm and quiet efficiency.</p><p>The hotel is particularly popular with solo trekkers and cyclists who appreciate the secure bike storage, knowledgeable travel desk, and the outstanding value breakfast included with each room. The rooftop terrace offers views of both the lake and the green hills to the east.</p>',
                'opening_hours' => 'Check-in: 12:00 PM | Check-out: 11:00 AM | Restaurant: 7:00 AM – 9:30 PM',
                'features' => $this->features(['Courtyard garden', 'Secure bicycle storage', 'Breakfast included', 'Rooftop terrace', 'Free Wi-Fi', 'Air conditioning', '24-hour reception', 'Knowledgeable travel desk', 'Safe deposit box', 'Laundry service', 'Daily housekeeping', 'Luggage storage']),
            ],
            'hotel-river-park' => [
                'description' => '<p>Hotel River Park is a peaceful property nestled beside the Seti River, one of Pokhara\'s most dramatic natural features — a milky-white glacial river that disappears underground through dramatic gorges and reappears at the river park just minutes from the hotel. This unique natural setting makes the hotel a base for white-water rafting, gorge exploration, and nature photography.</p><p>The hotel\'s riverside garden is one of Pokhara\'s most tranquil outdoor spaces, with the sound of the river providing a constant natural backdrop. Rafting operators and adventure guides operate from the hotel reception, making it easy to plan an action-packed day from the comfort of your room.</p>',
                'opening_hours' => 'Open 24 hours | Restaurant: 7:00 AM – 10:00 PM',
                'features' => $this->features(['Seti River location', 'Riverside garden', 'Rafting arrangement on-site', 'Gorge exploration tours', 'Nature photography base', 'Adventure sports centre', 'Free Wi-Fi', 'Air conditioning', 'Restaurant', 'Luggage storage', 'Laundry service', 'Airport transfer']),
            ],
            'hotel-mandala' => [
                'description' => '<p>Hotel Mandala draws its identity from the sacred circular mandala motif — a symbol of the universe, wholeness, and the interconnectedness of all things — that recurs throughout the hotel\'s décor, from hand-painted bedroom walls to the circular mosaic at the entrance. The overall effect is meditative and deeply beautiful.</p><p>The hotel is popular with artists, writers, and spiritually-inclined travellers who appreciate the visual richness of the space and the contemplative atmosphere. Regular cultural events include Tibetan Buddhist art workshops, thangka painting demonstrations, and evening readings on Himalayan philosophy. The rooftop meditation platform offers unbroken mountain views.</p>',
                'opening_hours' => 'Check-in: 12:00 PM | Check-out: 11:00 AM | Café & restaurant: 7:00 AM – 9:30 PM',
                'features' => $this->features(['Mandala-motif décor throughout', 'Rooftop meditation platform', 'Thangka painting workshops', 'Tibetan Buddhist art events', 'Himalayan philosophy evenings', 'Artist-in-residence programme', 'Free Wi-Fi', 'Air conditioning', 'Organic café', 'Meditation room', 'Laundry service', 'Airport transfer']),
            ],
            'international-youth-hostel-inn' => [
                'description' => '<p>International Youth Hostel Inn is Pokhara\'s most welcoming hub for backpackers, gap-year travellers, and budget-conscious adventurers from around the world. The hostel has been connecting travellers since its founding and maintains the spirit of the classic youth hostel tradition — affordable, social, and genuinely international.</p><p>The hostel offers dormitory beds, twin rooms, and private doubles, all maintained to a good standard of cleanliness. The communal kitchen allows self-catering, and the outdoor social terrace is a 24-hour gathering point where trekking groups form, travel tips are exchanged, and friendships begin. The friendly staff speak multiple languages and can arrange every activity in the Annapurna region.</p>',
                'opening_hours' => 'Open 24 hours | Kitchen: 6:30 AM – 10:00 PM',
                'features' => $this->features(['Dormitory & private rooms', 'Communal self-catering kitchen', '24-hour social terrace', 'Multilingual staff', 'Free Wi-Fi', 'Locker storage in dorms', 'Budget-friendly pricing', 'Trekking group formation', 'ACAP permit advice', 'Luggage storage', 'Laundry service', 'Tour booking available']),
            ],
        ];

        foreach ($hotels as $slug => $data) {
            Business::where('slug', $slug)->where('type', 'hotel')->update($data);
        }

        $this->command->info('Hotel detail seeding complete. ' . count($hotels) . ' hotel records targeted.');
    }

    private function seedRestaurantDetails(): void
    {
        $restaurants = [
            'bajeko-sekuwa' => [
                'description' => '<p>Bajeko Sekuwa is the Pokhara branch of Nepal\'s most celebrated roasted meat restaurant — an institution that has elevated sekuwa (Nepali wood-fire roasted meat) from street food to national culinary treasure. The Pokhara location maintains all the traditions of the Kathmandu original, with marinated buffalo and goat cooked over fragrant hardwood fires in open tandoor pits.</p><p>The sekuwa platters arrive sizzling on iron plates, accompanied by fresh salads, spiced pickles, and the house-made achaar that has become the restaurant\'s signature. The atmosphere is festive and communal — long tables, the warmth of the fires, and the irresistible aroma that draws queues every evening.</p>',
                'opening_hours' => '11:00 AM – 10:30 PM (open daily)',
                'features' => $this->features(['Wood-fire roasted sekuwa', 'Buffalo & goat specialties', 'Open tandoor pits', 'House-made achaar', 'Communal dining atmosphere', 'Group platters', 'Local craft beer', 'No alcohol-free option (beer served)', 'Takeaway available', 'Reservation recommended evenings']),
            ],
            'or2k-vegetarian-restaurant' => [
                'description' => '<p>OR2K Vegetarian Restaurant is a Pokhara landmark for vegetarian and vegan travellers — a colourful, cushion-filled dining space that has been nourishing herbivores from around the world for over two decades. Inspired by the Israeli restaurant of the same name in Kathmandu, OR2K serves a predominantly Middle Eastern and Mediterranean menu with strong vegetarian and vegan credentials.</p><p>Hummus, falafel, shakshuka, mezze boards, and fluffy pita breads are the cornerstones of a menu that changes little because guests keep returning for the same reliable classics. The cushioned floor seating and colorful tapestry décor create a relaxed, communal atmosphere that encourages lingering meals and lively conversation.</p>',
                'opening_hours' => '8:00 AM – 10:30 PM (open daily)',
                'features' => $this->features(['100% vegetarian & vegan', 'Middle Eastern & Mediterranean menu', 'House-made hummus & falafel', 'Cushion floor seating', 'Colourful tapestry décor', 'No meat, no fish', 'Fresh pita bread', 'Mezze boards', 'Juice bar', 'Free Wi-Fi']),
            ],
            'fresh-elements-restaurant-bar' => [
                'description' => '<p>Fresh Elements Restaurant & Bar is Pokhara\'s go-to destination for fresh, health-focused cuisine paired with a well-curated bar programme. The restaurant was conceived as a celebration of freshness — every dish is built around same-day-delivered ingredients, and the menu changes to reflect whatever is at its seasonal peak.</p><p>The kitchen operates with an open-plan design, allowing guests to watch the chefs at work. Highlights include the detox juice bar (20 varieties), grain bowls with Himalayan quinoa, and the ever-popular fresh fish tacos using lake trout. The bar offers natural wines, craft spirits, and inventive cocktails using fresh-pressed fruit and herb infusions.</p>',
                'opening_hours' => '8:00 AM – 11:00 PM (open daily)',
                'features' => $this->features(['Open-plan kitchen', 'Detox juice bar (20 varieties)', 'Seasonal fresh menu', 'Himalayan quinoa dishes', 'Fresh fish tacos', 'Natural wines', 'Craft cocktails', 'Vegan & gluten-free options', 'Free Wi-Fi', 'Reservation recommended']),
            ],
            'utopia-garden-snacks-bar' => [
                'description' => '<p>Utopia Garden & Snacks Bar is a beloved Lakeside institution — a garden café and casual bar that has been a favourite social spot for travellers and locals for many years. The relaxed garden setting, with hammocks, bean bags, and fairy lights among the mango trees, creates the kind of atmosphere where an intended 30-minute stop turns into an entire afternoon.</p><p>The menu is deliberately casual: wood-fired nachos, loaded wraps, grilled sandwiches, fresh juices, smoothies, and a selection of local and imported beers and cocktails. Happy hour (5–8 PM) with two-for-one cocktails is a Lakeside institution that draws a loyal evening crowd.</p>',
                'opening_hours' => '10:00 AM – 11:00 PM (open daily) | Happy hour: 5:00 PM – 8:00 PM',
                'features' => $this->features(['Garden hammocks & bean bags', 'Happy hour 5–8 PM (2-for-1)', 'Mango tree canopy setting', 'Wood-fired nachos', 'Smoothies & fresh juices', 'Beer garden', 'Casual snack menu', 'Board games', 'Free Wi-Fi', 'Live music occasional']),
            ],
            'the-juicery-cafe' => [
                'description' => '<p>The Juicery Café is Pokhara\'s dedicated health-and-wellness café, a bright, energetic space where cold-pressed juices, smoothie bowls, and plant-based food are the stars. Founded by a nutritionist and a chef who met while teaching at a Pokhara cooking school, the café is driven by a genuine belief in food as medicine.</p><p>The juice bar offers 35 cold-pressed varieties, from immunity boosters packed with ginger and turmeric to post-trek recovery blends with banana, peanut butter, and Himalayan salt. The food menu covers açaí bowls, avocado toasts, raw energy balls, and a rotating daily special. Everything is prepared without refined sugar, artificial additives, or MSG.</p>',
                'opening_hours' => '7:00 AM – 7:00 PM (Monday to Saturday) | 8:00 AM – 4:00 PM (Sunday)',
                'features' => $this->features(['35 cold-pressed juice varieties', 'Nutritionist-designed menu', 'No refined sugar or MSG', 'Açaí bowls', 'Post-trek recovery blends', 'Immunity booster shots', 'Raw food menu', 'Vegan & gluten-free', 'Free Wi-Fi', 'Takeaway bottles available']),
            ],
            'la-viva-restaurant-cafe' => [
                'description' => '<p>La Viva Restaurant & Café brings a Mediterranean warmth and vivacity to Lakeside Pokhara, with a menu that roams the coastlines of Italy, Spain, Greece, and the Middle East without apology. The terrace dining area, strung with terracotta pots, olive trees in planters, and warm amber lighting, is among the most inviting restaurant settings in the city.</p><p>Pizza from a wood-fired oven, handmade pasta with fresh pesto, Greek salad with locally made feta, Spanish-style grilled octopus, and Moroccan-spiced lamb — La Viva pulls off this ambitious range with consistent success. The wine list is one of the most thoughtfully curated in Pokhara, with a genuine effort to represent the regions the menu draws from.</p>',
                'opening_hours' => '11:00 AM – 10:30 PM (open daily)',
                'features' => $this->features(['Wood-fired pizza oven', 'Handmade pasta', 'Mediterranean terrace décor', 'Curated European wine list', 'Greek & Moroccan specialties', 'Locally made feta', 'Vegetarian Mediterranean menu', 'Reservation recommended', 'Live jazz Thursdays', 'Free Wi-Fi']),
            ],
            'samrat-tandoori-restaurant' => [
                'description' => '<p>Samrat Tandoori Restaurant has been one of Pokhara\'s most reliable and beloved Indian restaurants for over 15 years. Its clay tandoor ovens, burning with seasoned hardwood since early morning, produce the fragrant naan, succulent kebabs, and tender tikka dishes that have earned Samrat a devoted regular clientele.</p><p>The restaurant excels at the full spectrum of North Indian cuisine: rich butter chicken, silky dal makhani, crispy samosas, and the legendary mixed grill platter that arrives at the table with a theatrical flourish of smoke. The lunch thali offers extraordinary value, with 8–10 dishes for a fixed price that includes unlimited bread.</p>',
                'opening_hours' => '10:30 AM – 10:30 PM (open daily)',
                'features' => $this->features(['Clay tandoor ovens', '15-year established restaurant', 'Mixed grill platter', 'Lunch thali with unlimited bread', 'Butter chicken & dal makhani', 'Vegetarian Indian menu', 'Takeaway & delivery', 'Group bookings welcome', 'Private dining section', 'Free Wi-Fi']),
            ],
            'pokhara-family-restaurant' => [
                'description' => '<p>Pokhara Family Restaurant is exactly what a family restaurant should be: welcoming, unpretentious, reliably good, and priced so that families can eat without counting coins. Run by a large extended family whose children and grandchildren now help in the kitchen and at tables, the restaurant has served generations of both local and travelling families since 1992.</p><p>The menu covers traditional Nepali and Indian dishes with a few international crowd-pleasers for younger or less adventurous palates. The family dal bhat — enormous portions with four seasonal vegetable dishes, lentils, pickle, and curd — is considered among the best in Lakeside. Children\'s portions and menus are available upon request.</p>',
                'opening_hours' => '7:00 AM – 10:00 PM (open daily)',
                'features' => $this->features(['Family-run since 1992', 'Children\'s menu available', 'Best value dal bhat in Lakeside', 'Large portion sizes', 'Nepali, Indian & continental', 'Outdoor garden seating', 'Free Wi-Fi', 'Group tables', 'Takeaway available', 'High chairs for children']),
            ],
            'pokhara-chinese-restaurant' => [
                'description' => '<p>Pokhara Chinese Restaurant is the city\'s most authentic Chinese dining destination — a veteran establishment operated by a family with roots in the Sichuanese and Cantonese culinary traditions. The restaurant does not cater to a generic "Chinese food" expectation but instead serves the real, complex, and occasionally fiery flavours of regional Chinese cooking.</p><p>Signature dishes include mapo tofu with genuine Sichuan peppercorn heat, hand-pulled noodles in bone broth, steamed dim sum on weekend mornings, and a whole-fish preparation that is ordered weeks in advance by regular customers. The restaurant is small, unadorned, and focused entirely on the quality of the food.</p>',
                'opening_hours' => '11:00 AM – 9:30 PM (closed Mondays)',
                'features' => $this->features(['Authentic regional Chinese cuisine', 'Sichuan & Cantonese specialties', 'Hand-pulled noodles', 'Weekend dim sum', 'Mapo tofu signature dish', 'Whole fish preparation', 'Small & authentic atmosphere', 'No MSG claim', 'Vegetarian Chinese options', 'Cash preferred']),
            ],
            'adhunik-momo-hub' => [
                'description' => '<p>Adhunik Mo:Mo Hub is a modern (adhunik means "modern" in Nepali) take on Nepal\'s most loved food — the momo dumpling — with a menu that extends far beyond the traditional steamed buffalo variety to include an ever-expanding repertoire of innovative fillings, cooking styles, and presentation formats.</p><p>Tandoori momos baked in a clay oven, momo burgers served in brioche buns, chocolate and cream cheese dessert momos, and deconstructed momo soup in individual portions are just some of the creative interpretations on offer. The original steamed and fried classics remain available for purists. A dedicated momo cooking class runs on Saturday mornings.</p>',
                'opening_hours' => '10:00 AM – 9:30 PM (open daily)',
                'features' => $this->features(['Modern momo innovations', 'Tandoori momo in clay oven', 'Momo burger specialty', 'Dessert momos', 'Classic steamed & fried too', 'Momo cooking class Saturdays', 'All momo varieties', 'Budget-friendly', 'Takeaway available', 'Free Wi-Fi']),
            ],
            'roadhouse-cafe-pokhara' => [
                'description' => '<p>Roadhouse Café Pokhara is the city\'s original American-style diner — a high-energy, music-filled venue that has been the after-trek celebration destination of choice since its founding. With a wood-and-brick interior, neon signs, vintage rock posters, and a jukebox that plays classic rock, country, and blues, Roadhouse creates an atmosphere that feels a world away from the Himalayas and yet entirely at home in it.</p><p>The menu is unapologetically American: double cheeseburgers with hand-cut fries, BBQ ribs with coleslaw, loaded potato skins, chilli con carne, and a dessert menu anchored by the legendary house brownie with vanilla ice cream. The bar carries an exceptional selection of American whiskey and craft spirits.</p>',
                'opening_hours' => '11:00 AM – 11:30 PM (open daily)',
                'features' => $this->features(['American-style diner', 'Classic rock & blues atmosphere', 'BBQ ribs & burgers', 'Hand-cut fries', 'American whiskey bar', 'Craft spirits selection', 'Live music weekends', 'Happy hour 5–7 PM', 'Group bookings', 'Free Wi-Fi']),
            ],
            'little-big-cafe-pokhara' => [
                'description' => '<p>Little Big Café is Pokhara\'s most delightful contradiction — a tiny venue with enormous ambition, a small menu executed to a standard that punches well above its compact footprint. The café seats only 22 people and the kitchen has space for two, but the quality of what emerges from that kitchen has earned it a reputation that far exceeds its size.</p><p>The concept is simple: a handful of dishes, sourced from the best local producers, prepared with serious culinary skill, and served in a space designed to feel like a friend\'s living room. The coffee is outstanding, the eggs benedict is a Lakeside legend, and the weekend brunch waitlist begins the moment the door opens at 8 AM.</p>',
                'opening_hours' => '8:00 AM – 4:00 PM (Tue to Sun, closed Mondays)',
                'features' => $this->features(['22-seat intimate café', 'Specialty coffee', 'Eggs Benedict legend', 'Weekend brunch waitlist', 'Locally sourced produce', 'Friend\'s living room atmosphere', 'Small but perfectly executed menu', 'Natural light space', 'Free Wi-Fi', 'Cash only']),
            ],
            'nirvana-terrace-bar-lounge' => [
                'description' => '<p>Nirvana Terrace Bar & Lounge is Pokhara\'s most atmospheric evening venue — a rooftop terrace bar positioned above the Lakeside rooftops, where the Annapurna range forms the backdrop to every cocktail and conversation. The name references both the Buddhist concept of ultimate peace and the feeling guests consistently describe when they first take in the view.</p><p>The cocktail programme is the finest in Lakeside, led by a trained mixologist who creates seasonal menus using local herbs, mountain honey, Himalayan salt, and Nepali spirits. The lounge serves sophisticated bar snacks — bruschetta, cheese boards, charcuterie — designed to complement rather than overshadow the drinks. Live acoustic performances most evenings from 7 PM.</p>',
                'opening_hours' => '4:00 PM – midnight (open daily) | Kitchen closes 10:30 PM',
                'features' => $this->features(['Rooftop Annapurna views', 'Award-winning cocktail programme', 'Local herb & honey cocktails', 'Himalayan salt specialties', 'Live acoustic evenings from 7 PM', 'Cheese boards & charcuterie', 'Nepali craft spirits', 'Sunset golden hour', 'Reservation recommended', 'Premium wine selection']),
            ],
            'pokhara-pizza-house' => [
                'description' => '<p>Pokhara Pizza House has been feeding pizza-hungry travellers since the early days of Pokhara\'s tourist boom, and its dedication to wood-fired, slow-fermented pizza dough has never wavered. The sourdough base — proved for a minimum of 48 hours — creates a crust with a complex, slightly tangy flavour and the perfect balance of crisp and chewy.</p><p>Toppings cover the classics (margherita, pepperoni, quattro formaggi) alongside inventive Nepali-inspired combinations: yak cheese and forest mushroom, buffalo mozzarella with local Himalayan herbs, and the popular "Annapurna" pizza with smoked chicken, caramelised onions, and house chilli oil. Available by the slice from 12 PM.</p>',
                'opening_hours' => '11:00 AM – 10:30 PM (open daily) | By-the-slice from 12:00 PM',
                'features' => $this->features(['48-hour proved sourdough dough', 'Wood-fired oven', 'By-the-slice from noon', 'Yak cheese topping', 'Nepali herb combinations', 'Classic Italian and original options', 'Takeaway & delivery', 'Vegan cheese available', 'Free Wi-Fi', 'Group orders welcome']),
            ],
            'pokhara-thakali-kitchen' => [
                'description' => '<p>Pokhara Thakali Kitchen is the city\'s most revered destination for authentic Thakali cuisine — the distinctive culinary tradition of the Thakali people of the Kali Gandaki valley in Mustang district. Thakali food sits at the intersection of Tibetan and Nepali cooking, with a character all its own: deeply aromatic, richly spiced, and built for mountain altitudes.</p><p>The signature Thakali set meal is a revelation: a copper thali with buckwheat bread, yak butter rice, five or six revolving vegetable and meat dishes, thick lentil soup, and the house-made timur pickle that sparks the lips with Sichuan-like heat. The restaurant sources directly from Thakali farming families in Mustang and Baglung districts.</p>',
                'opening_hours' => '10:30 AM – 9:30 PM (open daily)',
                'features' => $this->features(['Authentic Thakali cuisine', 'Copper thali service', 'Buckwheat bread specialty', 'Timur (Sichuan pepper) pickle', 'Direct Mustang sourcing', 'Yak butter dishes', 'Seasonal vegetable rotation', 'Vegetarian Thakali available', 'No artificial additives', 'Takeaway thali available']),
            ],
            'taal-restro-bar' => [
                'description' => '<p>Taal Restro & Bar (taal meaning "lake" in Nepali) is a vibrant lakeside venue that perfectly captures the festive energy of Pokhara\'s evening Lakeside scene. With a terrace directly overlooking Phewa Lake, a full bar, and a music policy that keeps the energy high without overpowering conversation, Taal has become a default evening venue for both first-timers and returning visitors.</p><p>The food menu covers all the popular categories: wood-fired pizza, pasta, burgers, Nepali plates, and a comprehensive momo section. The bar is particularly strong on local Nepal Ice craft beers and a cocktail list that makes creative use of locally distilled raksi spirits. DJ sets on Friday and Saturday evenings from 9 PM.</p>',
                'opening_hours' => '11:00 AM – midnight (Fri & Sat until 1:00 AM)',
                'features' => $this->features(['Lakeside terrace', 'DJ sets Fri & Sat from 9 PM', 'Nepal Ice craft beers', 'Local raksi cocktails', 'Wood-fired pizza', 'Full momo menu', 'Live sport TV screens', 'Happy hour 5–8 PM', 'Group bookings', 'Free Wi-Fi']),
            ],
            'tree-house-restro' => [
                'description' => '<p>Tree House Restro is Pokhara\'s most whimsical dining destination — a restaurant built around and through a magnificent old banyan tree, with dining platforms at multiple levels connected by wooden walkways, rope bridges, and spiral staircases. Eating here, among the tree\'s sprawling branches, is an experience that delights adults and absolutely thrills children.</p><p>The menu is broad and approachable, spanning Nepali comfort food, Indian curries, continental classics, and a comprehensive children\'s menu. The higher platforms, accessible by the steeper staircases, offer treetop views of the surrounding neighbourhood and glimpses of the Annapurna range. Sunset drinks on the top deck are a particularly popular activity.</p>',
                'opening_hours' => '8:00 AM – 10:00 PM (open daily)',
                'features' => $this->features(['Built into a live banyan tree', 'Multi-level treehouse platforms', 'Rope bridges & spiral staircases', 'Treetop mountain views', 'Children\'s menu', 'Family-friendly', 'Broad international menu', 'Sunset top-deck drinks', 'Free Wi-Fi', 'Group bookings']),
            ],
            'cafe-camellia-pokhara' => [
                'description' => '<p>Café Camellia is named after the camellia sinensis plant — the source of all true teas — and this devotion to the art of tea is the café\'s defining character. With a menu spanning over 60 varieties of Nepali, Indian, Chinese, Japanese, and blended teas, Café Camellia offers a tea education as well as a dining experience.</p><p>The food menu complements the tea philosophy with light, refined dishes: finger sandwiches, scones with clotted cream, tea-infused cakes, and afternoon tea sets that offer a Himalayan take on the English tradition. The café also hosts monthly tea tastings and serves as an outlet for selected Ilam and Annapurna region tea estates.</p>',
                'opening_hours' => '8:00 AM – 8:00 PM (open daily) | Monthly tea tasting: first Saturday',
                'features' => $this->features(['60+ tea varieties', 'Nepali Ilam tea specialist', 'Afternoon tea sets', 'Scones & clotted cream', 'Tea-infused cakes', 'Monthly tea tasting events', 'Tea estate retail', 'No alcohol served', 'Quiet contemplative atmosphere', 'Free Wi-Fi']),
            ],
            'the-kebab-king' => [
                'description' => '<p>The Kebab King reigns supreme in Pokhara\'s street food scene — a counter-style restaurant that has elevated the art of the grilled kebab to royal heights. Open-air charcoal grills visible from the street produce the smoke signal that draws meat lovers from across Lakeside every evening.</p><p>The menu is focused and confident: seekh kebab, boti kebab, chicken tikka, reshmi kebab, and shami kebab, each marinated in house-ground spice blends and grilled to order over live charcoal. Wraps, rolls, and rice plates are available for a complete meal. The Kebab King sauce — a house-made chilli and herb condiment — has developed a cult following.</p>',
                'opening_hours' => '12:00 PM – 10:30 PM (open daily)',
                'features' => $this->features(['Live charcoal grill visible', 'House-ground spice marinades', 'Seekh & boti kebabs', 'Chicken tikka specialty', 'Cult-status Kebab King sauce', 'Kebab wraps & rolls', 'Budget-friendly', 'Takeaway available', 'Counter dining', 'Catering available']),
            ],
            'caffe-concerto' => [
                'description' => '<p>Caffè Concerto brings the convivial spirit of an Italian café bar to the shores of Phewa Lake. The name evokes a musical gathering — and true to this, the café plays a carefully curated mix of Italian jazz, classical guitar, and acoustic pop that creates an atmosphere perfectly suited to lingering espressos, shared pasta, and relaxed conversation.</p><p>The espresso programme uses a house-blend of Italian and Nepali single-origin beans, roasted by a partner in Kathmandu and pulled through a La Marzocco machine — arguably the best espresso in Pokhara. The kitchen produces fresh pasta daily, with four sauces rotating on a weekly basis, accompanied by excellent antipasti and a concise Italian wine selection.</p>',
                'opening_hours' => '8:00 AM – 10:30 PM (open daily)',
                'features' => $this->features(['Italian-Nepali coffee blend', 'La Marzocco espresso machine', 'Fresh pasta daily', 'Italian jazz atmosphere', 'Antipasti selection', 'Italian wine list', 'Aperitivo hour 6–8 PM', 'Tiramisu signature dessert', 'Free Wi-Fi', 'Outdoor lakeside tables']),
            ],
            'moondance-restaurant-bar' => [
                'description' => '<p>Moondance Restaurant & Bar is a romantic Lakeside dining destination that has perfected the formula of great food, warm lighting, and an atmosphere that makes every meal feel like a celebration. The open terrace overlooks a quiet stretch of the Lakeside promenade, ideal for evenings when the stars reflect in Phewa Lake.</p><p>The menu is an eclectic world tour: Mediterranean mezze, Japanese ramen, Mexican tacos, and Nepali mountain cheeses alongside perfectly executed steaks and fresh-caught trout. The cocktail list features house-infused spirits and fresh mountain herbs. Live acoustic guitar performances run Wednesday and Saturday evenings.</p>',
                'opening_hours' => '11:00 AM – 11:00 PM (open daily)',
                'features' => $this->features(['Romantic lakeside terrace', 'Live acoustic guitar Wed & Sat', 'Eclectic world cuisine', 'Fresh local trout', 'Creative cocktail list', 'House-infused spirits', 'Full bar & wine list', 'Vegan-friendly options', 'Reservation recommended', 'Free Wi-Fi']),
            ],
            'daddys-kitchen' => [
                'description' => '<p>Daddy\'s Kitchen is a homestyle Nepali and Indian restaurant where the owner-chef — universally known as "Daddy" — has been cooking for travellers and locals with the generous spirit of a family patriarch since 1999. The restaurant is beloved for its enormous portions, house-made pickles, and the famous "Daddy\'s Special" — a daily changing curry prepared from whatever looks best at the morning market.</p><p>The dhido (buckwheat porridge) with gundruk (fermented greens) and Daddy\'s chicken curry are the dishes that keep regulars coming back year after year. Every table gets a complimentary bowl of house-made yoghurt to start and a small sweet to finish — gestures of hospitality that reflect the owner\'s character.</p>',
                'opening_hours' => '7:30 AM – 10:00 PM (open daily)',
                'features' => $this->features(['Owner-chef "Daddy" since 1999', 'Enormous home-cooked portions', 'Daily Daddy\'s Special curry', 'House-made pickles', 'Complimentary yoghurt & sweets', 'Traditional dhido & gundruk', 'Budget-friendly prices', 'Family atmosphere', 'Vegetarian options', 'Takeaway available']),
            ],
            'krazy-gecko' => [
                'description' => '<p>Krazy Gecko is a Lakeside institution with a personality as big and colourful as its name — a loud, fun, unpretentious bar and restaurant that has been hosting celebrations, reunions, and spontaneous adventures since the early 2000s. The gecko motif appears throughout the décor in dozens of forms, from painted murals to ceramic figurines to the neon sign that has become one of Lakeside\'s most recognisable landmarks.</p><p>The food menu covers the bases that hungry, happy travellers need: good burgers, loaded nachos, fish and chips, pasta, and an extensive pizza menu. The bar stocks everything from local Everest beer to premium spirits, and the weekly quiz night (Wednesday, 7 PM) draws the best-informed crowd in Pokhara.</p>',
                'opening_hours' => '10:00 AM – midnight (open daily) | Quiz night: Wednesdays 7:00 PM',
                'features' => $this->features(['Lakeside institution', 'Weekly quiz night Wednesdays', 'Gecko-themed décor', 'Great burgers & pizza', 'Full bar', 'Loaded nachos', 'Fish & chips', 'Live sport TV', 'Happy hour', 'Free Wi-Fi']),
            ],
            'almonds-cafe-restaurant' => [
                'description' => '<p>Almond\'s Café & Restaurant is a calm, light-filled café that uses the almond as a culinary metaphor for its philosophy — something simple, nutritious, and endlessly versatile. The café specialises in healthy, whole-food cooking with an international range that effortlessly spans breakfast, lunch, and dinner without losing coherence or quality.</p><p>Almond granola bowls, almond-milk lattes, almond pesto pasta, and almond-crusted fish are examples of how the café builds signature dishes around its namesake ingredient. Beyond the almond theme, the menu offers a broad range of plant-based and omnivore options, all prepared with fresh local ingredients and genuine care.</p>',
                'opening_hours' => '7:30 AM – 9:30 PM (open daily)',
                'features' => $this->features(['Healthy whole-food cooking', 'Almond-based signature dishes', 'Almond-milk latte', 'International menu', 'Plant-based options', 'Fresh local ingredients', 'Bright & airy atmosphere', 'Free Wi-Fi', 'Laptop-friendly', 'Takeaway available']),
            ],
            'momotarou-japanese-restaurant' => [
                'description' => '<p>Momotarou Japanese Restaurant is Pokhara\'s only dedicated Japanese dining destination — a genuine slice of Japan in the Himalayan foothills. Founded by a Japanese chef who relocated to Nepal after working in Tokyo and Kyoto restaurants, Momotarou brings authentic Japanese culinary discipline to a setting that provides its own extraordinary context.</p><p>The menu spans ramen (six broth styles), sushi and sashimi using Himalayan river fish and imported salmon, udon, gyoza, and a carefully selected Japanese whisky collection. The restaurant follows the Japanese ethos of shokunin — craftsman spirit — in every dish, from the precision of the sushi rice temperature to the clarity of the dashi broth.</p>',
                'opening_hours' => '12:00 PM – 9:30 PM (closed Tuesdays)',
                'features' => $this->features(['Authentic Japanese cuisine', 'Japanese chef-trained in Tokyo', 'Ramen with 6 broth styles', 'Sushi & sashimi', 'Himalayan river fish', 'Japanese whisky selection', 'Gyoza & udon', 'Shokunin craftsmanship', 'Reservation recommended', 'No substitutions in ramen']),
            ],
            'the-lemon-tree-restaurant' => [
                'description' => '<p>The Lemon Tree Restaurant is a bright, citrus-coloured café-restaurant that has been one of the most consistently excellent dining spots in Lakeside for over a decade. Its lemon tree motif — representing freshness, sourness, and the unexpected burst of flavour that lifts any dish — informs a menu built around bold, clean flavours and quality ingredients.</p><p>The restaurant excels at breakfast (the lemon ricotta pancakes have a devoted following), lunch (the lemon-herb chicken wrap is a perennial bestseller), and dinner (the lemon curd tart with house cream is a must-order dessert). The terrace, shaded by a genuine lemon tree in a large pot, is among the most sought-after seats in Lakeside.</p>',
                'opening_hours' => '7:30 AM – 10:00 PM (open daily)',
                'features' => $this->features(['Lemon ricotta pancakes', 'Terrace seating under lemon tree', 'Breakfast, lunch & dinner', 'Lemon curd tart dessert', 'Fresh herb garden kitchen', 'Free high-speed Wi-Fi', 'Vegetarian & vegan options', 'Daily fresh-squeezed lemonade', 'Takeaway available', 'Group bookings']),
            ],
            'vegan-way' => [
                'description' => '<p>Vegan Way is Pokhara\'s pioneering vegan restaurant — a bright, modern space that has been challenging the notion that Nepali cuisine cannot be fully vegan since its founding. The kitchen proves otherwise with a menu that demonstrates the astonishing richness and variety of plant-based Nepali and international cooking.</p><p>The fully vegan menu includes authentic Nepali dishes prepared without any animal products: vegan dal bhat with eight vegetable preparations, vegan momos filled with jackfruit and tofu, vegan sekuwa using marinated tempeh, and a celebrated vegan milk tea made with cashew milk and Ilam tea. The restaurant uses zero single-use plastic and composts all kitchen waste.</p>',
                'opening_hours' => '8:00 AM – 9:30 PM (open daily)',
                'features' => $this->features(['100% vegan menu', 'Vegan Nepali cuisine specialist', 'Jackfruit & tofu momos', 'Tempeh sekuwa', 'Cashew milk Ilam tea', 'Zero single-use plastic', 'Compost kitchen waste', 'No animal products', 'Vegan dal bhat', 'Free Wi-Fi']),
            ],
            'rosemary-kitchen' => [
                'description' => '<p>Rosemary Kitchen is a long-standing Lakeside favourite that draws its name and culinary identity from the fragrant herb that runs through so many of its dishes. The restaurant combines reliable European comfort food with a warm, herb-garden aesthetic — rosemary wreaths on the walls, potted herbs on every table, and the scent of wood-roasted garlic and rosemary drifting from the kitchen throughout service.</p><p>Rosemary roast chicken, lamb with rosemary and lemon, rosemary flatbread with olive oil, and rosemary panna cotta are among the signature dishes that have made this restaurant a weekly ritual for Pokhara\'s expatriate community. The wine list is concise but carefully chosen, with the emphasis on value and food compatibility.</p>',
                'opening_hours' => '11:00 AM – 10:30 PM (open daily)',
                'features' => $this->features(['Rosemary herb-focused cuisine', 'European comfort food', 'Rosemary roast chicken', 'Wood-roasted garlic', 'Herb garden aesthetic', 'Expatriate favourite', 'Concise wine list', 'Rosemary panna cotta', 'Vegetarian options', 'Free Wi-Fi']),
            ],
            'tibetan-yak' => [
                'description' => '<p>Tibetan Yak is Pokhara\'s most authentic Tibetan restaurant — a warm, incense-scented space decorated with traditional thangka paintings, butter lamps, and hand-carved wooden furniture that creates the atmosphere of a traditional Tibetan household. The restaurant has been run by a family of Tibetan refugees for over 25 years with pride and cultural integrity.</p><p>The menu centres on the hearty, nourishing food that sustained Tibetan communities across the high plateau: thenthuk (flat hand-torn noodle soup), shyakpa (meat and vegetable stew), sha balep (meat-filled flatbread), and an exceptional Tibetan hot pot available for groups of four or more. Yak butter tea and chang (fermented barley beer) are the traditional drink accompaniments.</p>',
                'opening_hours' => '10:00 AM – 9:30 PM (open daily)',
                'features' => $this->features(['Authentic Tibetan family restaurant', 'Thenthuk & shyakpa specialties', 'Sha balep (meat flatbread)', 'Tibetan hot pot (4+ guests)', 'Yak butter tea', 'Chang fermented beer', 'Thangka art & butter lamps', 'No pork served', 'Vegetarian Tibetan menu', 'Cultural atmosphere']),
            ],
            'med5-restaurant' => [
                'description' => '<p>Med5 Restaurant is named for the five signature spice blends that the chef developed over years of culinary training across South Asia and the Mediterranean. These five blends — Himalayan, Moroccan, Lebanese, Indian, and Greek — are the backbone of a menu that ranges widely but always maintains a coherent spice-forward identity.</p><p>The result is a menu that finds unexpected harmony: a Himalayan-spiced lamb chop with Moroccan couscous, a Lebanese-inspired mezze plate with Indian chutneys, and a Greek salad with Himalayan salt and local cheese. Med5 has developed a loyal following among Pokhara\'s food-forward community who appreciate its thoughtful, creative approach to global flavours.</p>',
                'opening_hours' => '11:30 AM – 10:30 PM (open daily)',
                'features' => $this->features(['Five signature spice blends', 'Himalayan-Mediterranean fusion', 'Moroccan couscous', 'Lebanese mezze plates', 'Greek salad with local cheese', 'Thoughtful cross-cultural menu', 'Full bar & wine list', 'Reservation recommended', 'Vegetarian fusion menu', 'Free Wi-Fi']),
            ],
            'san-chon-korean-restaurant' => [
                'description' => '<p>San Chon Korean Restaurant brings the communal, fire-at-the-table experience of Korean BBQ to Pokhara — the only restaurant in the valley to do so authentically. Each table is equipped with a built-in charcoal grill, and the parade of small dishes (banchan) that precede the main grill items is a meal in itself.</p><p>The menu covers the Korean BBQ essentials: samgyeopsal (thick-cut pork belly), bulgogi (marinated beef), dak-galbi (spicy chicken), and galbi (short ribs), alongside Korean classics like bibimbap, japchae, and the spicy kimchi jjigae stew. The house-made kimchi, fermented on-site, is exceptional.</p>',
                'opening_hours' => '12:00 PM – 10:00 PM (closed Sundays)',
                'features' => $this->features(['Table charcoal grills', 'Authentic Korean BBQ', 'House-made fermented kimchi', 'Banchan (side dish) service', 'Samgyeopsal pork belly', 'Bibimbap & japchae', 'Korean soju & makgeolli', 'Group dining specialist', 'Reservation recommended', 'Vegetarian Korean available']),
            ],
            'pokhara-sekuwa-house' => [
                'description' => '<p>Pokhara Sekuwa House is dedicated entirely to the art of sekuwa — the ancient Nepali tradition of marinating meat in spices and wood-fire roasting it over hardwood embers. The restaurant has perfected its technique over many years, and the result is sekuwa of such quality that the restaurant supplies several hotel restaurants in Pokhara.</p><p>The house marinade is a closely guarded recipe of over 20 spices and herbs, including jimbu, timur, and local wild oregano. Buffalo sekuwa, mutton sekuwa, chicken sekuwa, and the premium Himalayan yak sekuwa (available seasonally) are the main offerings. Everything is served with sautéed greens, beaten rice (chiura), and the house hot sauce.</p>',
                'opening_hours' => '11:00 AM – 10:00 PM (open daily)',
                'features' => $this->features(['Sekuwa specialist restaurant', '20+ spice house marinade', 'Jimbu & timur seasoning', 'Yak sekuwa seasonal special', 'Buffalo & mutton options', 'Served with chiura (beaten rice)', 'Charcoal hardwood fire', 'House hot sauce', 'Takeaway available', 'Catering service available']),
            ],
        ];

        foreach ($restaurants as $slug => $data) {
            Business::where('slug', $slug)->where('type', 'restaurant')->update($data);
        }

        $this->command->info('Restaurant detail seeding complete. ' . count($restaurants) . ' restaurant records targeted.');
    }
}
